# Generated by Django 2.0.2 on 2018-04-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180418_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={},
        ),
    ]
