# Generated by Django 2.0.2 on 2018-04-18 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180418_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 18, 6, 37, 51, 637730, tzinfo=utc)),
        ),
    ]
