# Generated by Django 2.0.2 on 2018-04-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180419_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
